# Site settings
title: TheMagnificent11's Blog
description: A .Net engineer's thoughts on domain-driven design, observability, and software engineering
author: Saji Weerasingham
url: "https://themagnificent11.github.io"
baseurl: "/themagnificent11"

# Build settings
theme: jekyll-theme-midnight
markdown: kramdown
permalink: /posts/:year-:month-:day-:title/

# Include/Exclude settings
exclude:
  - .git
  - .github
  - README.md
  - Gemfile
  - Gemfile.lock
  - wip

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
